[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hi-sdk"
version = "0.1"
description = "LLM Development Kit for Raspberry Pi"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"} 